// Generated by CoffeeScript 1.6.3
var fs, soma;

fs = require('fs');

soma = require('soma');

exports.init = function() {
  var key, packageJSON, value, _ref;
  soma.config = {
    compress: true,
    inlineScripts: false,
    inlineStylesheets: false,
    app: ['app'],
    api: ['api']
  };
  packageJSON = require(process.cwd() + '/package');
  _ref = packageJSON.soma;
  for (key in _ref) {
    value = _ref[key];
    soma.config[key] = value;
  }
};
