// Generated by CoffeeScript 1.3.3
var fs, soma,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require('fs');

soma = require('soma');

exports.init = function() {
  var dep, key, packageJSON, value, _ref;
  soma.config = {
    compress: true,
    inlineScripts: false,
    inlineStylesheets: false,
    app: ['app'],
    api: ['api']
  };
  packageJSON = require(process.cwd() + '/package');
  _ref = packageJSON.soma;
  for (key in _ref) {
    value = _ref[key];
    soma.config[key] = value;
  }
  for (dep in packageJSON.dependencies) {
    if (__indexOf.call(require(dep + '/package').keywords, 'soma') >= 0) {
      require(dep);
    }
  }
};
